<template>
  <div class="Footer">
    <a href="http://almawashington.com" target="_blank">Portfolio</a> |
       <a href="https://github.com/alma19" target="_blank">Github</a> |
       <a href="/">Credits</a> |
       <a href="/styleguide">Styleguide</a> |
       <a href="/">Documentation</a>
  </div>
</template>

<script>
export default {
}
</script>

<style scoped>
.Footer {
  background-color: #7e6e81;
  margin-top: 5%;
  text-align: center;
  padding: 15px;
  color: black;
}

a {
  color: black;
  text-decoration: none;
}

a:hover {
  color: white;
  text-decoration: none; 
}
</style>
