<template>
  <div class="ShowFooter">
    <a href="http://almawashington.com" target="_blank">Portfolio</a> |
       <a href="https://github.com/alma19" target="_blank">Github</a> |
       <a href="/styleguide">Styleguide</a> |
       <a href="https://alma19.gitbooks.io/show-tracker-api/content/" target="_blank">Documentation</a> |
       <a href="http://codepen.io/katehoover/pen/wBoQXL" target="_blank">Loader Component</a>
  </div>

</template>

<script>
export default {
}
</script>

<style scoped lang="scss">
.ShowFooter {
  background-color: #7e6e81;
  margin-top: 5%;
  text-align: center;
  padding: 15px;
  color: black;
}

a {
  color: black;
  text-decoration: none;
}

a:hover {
  color: white;
  text-decoration: none;
}
</style>
